### ISSUE TITLE
Proposed change in description of repo.

### ISSUE THREAD

**Issue by melodykramer** [18F/cf-provision-user-space-plugin#3]
Hey!

I'm doing a quick audit of all of 18F's GitHub repos to make sure that descriptions, ReadMe's, and issues are written as concisely and descriptively as they can be. This will help other organizations who would like to adapt our code as well as the public — who may be interested in adapting our code or contributing to our repos.

**The current title of this repo is:** 

**Would it be possible to change it to:** This is a plugin for Cloud Foundry CLI. This plugin effectively creates a new cf user, an organization (if specified) and a personal space within the sandbox organization.

That way, anyone who comes across it [here](https://github.com/18F) or on GovCode will know exactly what the repo contains.

Thank you! Your ReadME looks great!

Mel

**Comment by afeld** [comment]
Updated!
